import { Layout } from '@/components/layout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout title="Roberto" subTitle="Aleydon">
        <h3>Content</h3>
      </Layout>
    </>
  );
}
